name: Bug Report
description: File a bug report.
title: "Bug: "
body:
  - type: markdown
    attributes:
      value: |
        We appreciate you taking the time to report a bug. Please fill out the information below to the best of your ability.
        Before submitting your issue, please check to see if it has already been reported.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Tell us what happened
      value: "My game crashed!"
    validations:
      required: true
  - type: textarea
    id: what-should-happen
    attributes:
      label: What should have happened?
      placeholder: Tell us what should have happened
      value: "The game should have loaded"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Arc are you using?
    validations:
      required: true
  - type: input
    id: logs
    attributes:
      label: Log Output
      description: Please copy the entire log file located in `.minecraft/logs/latest.log` to [MCLogs](https://mclo.gs) and provide the link here.
